spring.application.name=api-gateway
server.port=8080

# Downstream Microservice URLs
services.attack-service.url=http://localhost:8081
services.analytics-service.url=http://localhost:8083
services.ml-service.url=http://localhost:8000
